# Estatística Aplicada a Ciência de Dados: Lista de Exercícios - 02

01. Numa tabela, cada linha representa:

> (a) um indivíduo.
>
> (b) um atributo ou variável.

In [3]:
# @title  { run: "auto", vertical-output: true }

q1 = '(a)' #@param[' ', '(a)', '(b)']

answer = '(a)'

if q1 == answer:
  print('Resposta correta.')

else:
  print('Reveja a sua resposta.')

Resposta correta.

02. Numa tabela, cada coluna representa:

> (a) um indivíduo.
>
> (b) um atributo ou variável.

In [4]:
# @title  { run: "auto", vertical-output: true }

q2 = '(b)' #@param[' ', '(a)', '(b)']

answer = '(b)'

if q2 == answer:
  print('Resposta correta.')

else:
  print('Reveja a sua resposta.')

Resposta correta.

03. Na tabela abaixo

|     |Dia|Hora   |Local    |
|:---:|:-:|:-----:|:-------:|
|**0**|  3|15 h 20|Curitiba |
|**1**|  5|11 h 13|São Paulo|
|**2**| 11|08 h 11|Campinas |

Os números em negrito da primeira coluna (0, 1 e 2) representam:

> (a) o índice dos atributos.
>
> (b) o tempo em milisegundos para a inserção dos valores naquela linha.
>
> (c) são valores aleatórios que o *pandas* insere para o seu autocontrole de execução.
>
> (d) o índice do indivíduo.
>
> (e) o índice das variáveis.

In [6]:
# @title  { run: "auto", vertical-output: true }

q3 = '(d)' #@param[' ', '(a)', '(b)', '(c)', '(d)', '(e)']

answer = '(d)'

if q3 == answer:
  print('Resposta correta.')

else:
  print('Reveja a sua resposta.')

Resposta correta.

04. Usando a tabela presente no *link* a seguir, faça o que se pede:

> [https://raw.githubusercontent.com/nightlySnoopy/database/main/titanic.csv](https://raw.githubusercontent.com/nightlySnoopy/database/main/titanic.csv)

(a) Chame a biblioteca *pandas* e utilize como *alias pd*.

In [7]:
import pandas as pd

(b) Atribua a tabela do link acima ao nome df4.

In [13]:
df4 = pd.read_csv("https://raw.githubusercontent.com/nightlySnoopy/database/main/titanic.csv")

(c) Visualize as 8 primeiras linhas dessa tabela usando o método *.head()*.

In [14]:
df4.head(8)

,PassengerId,Survived,Pclass,Name,Sex,Age,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,7.2500,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,7925.0000,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,Southampton
4,5,0,3,"Allen, Mr. William Henry",male,35.0,8.0500,Southampton
5,6,0,3,"Moran, Mr. James",male,NaN,8.4583,Queenstown
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,51.8625,Southampton
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,21075.0000,Southampton

(d) Visualize as 5 últimas linhas dessa tabela usando o método *.tail()*.

In [15]:
df4.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,Fare,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,13.00,Southampton
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,30.00,Southampton
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,23.45,Southampton
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,30.00,Cherbourg
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,7.75,Queenstown

(e) Usando o método *.shape*, verifique quantas linhas e quantas colunas essa tabela apresenta.

In [16]:
df4.shape

(891, 8)

(f) Usando o método *.columns*, verifique o nome das colunas dessa tabela.

In [17]:
df4.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Fare',
       'Embarked'],
      dtype='object')

(g) Usando o método *.info( )*, verifique a classificação dos valores presentes em cada uma das colunas da tabela *df4*.

In [18]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   Fare         891 non-null    float64
 7   Embarked     889 non-null    object
dtypes: float64(2), int64(3), object(3)
memory usage: 55.8+ KB

05. A tabela a seguir foi construída com dados de um conjunto de gestantes de um hospital norte americano na tentativa de verificar a influência do cigarro na massa do recém nascido. De forma geral, quanto menor a massa de um recém nascido, maiores são as chances dele ter alguma problema de saúde após seu nascimento.

> [https://raw.githubusercontent.com/nightlySnoopy/database/main/birth.csv](https://raw.githubusercontent.com/nightlySnoopy/database/main/birth.csv)

As colunas presentes nessa tabela são:

* *Birth Weight*: massa em onça do bebê recém-nascido (1 onça $\equiv$ 	28.35 gramas);

* *Gestational Days*: número de dias gestacionais;

* *Maternal Age*: a idade da mãe completa em anos;

* *Maternal Height*: a altura da mãe em em polegadas (1 polegada $\equiv$ 2.54 centímetros);

* *Maternal Pregnancy Weight*: a massa da gestante em libras (1 libra $\equiv$ 0.4536 quilograma);

* *Maternal Smoker*: se a mãe fumou ou não durante a gestação.

(a) Atribua a tabela do link acima ao nome df5.

In [21]:
df5 = pd.read_csv("https://raw.githubusercontent.com/nightlySnoopy/database/main/birth.csv")

(b) Visualize as 5 primeiras linhas dessa tabela:

In [23]:
df5.head(5)

,Birth Weight,Gestational Days,Maternal Age,Maternal Height,Maternal Pregnancy Weight,Maternal Smoker
0,120,284,27,62,100,False
1,113,282,33,64,135,False
2,128,279,28,64,115,True
3,108,282,23,67,125,True
4,136,286,25,62,93,False

(c) Visualize apenas a coluna *Gestational Days*.

In [32]:
df5[['Gestational Days']]

      Gestational Days
0                  284
1                  282
2                  279
3                  282
4                  286
...                ...
1169               275
1170               265
1171               291
1172               281
1173               297

[1174 rows x 1 columns]

(d) Visualize apenas a coluna *Gestational Days* e *Maternal Smoker*.

In [33]:
df5[['Gestational Days', 'Maternal Smoker']]

      Gestational Days  Maternal Smoker
0                  284            False
1                  282            False
2                  279             True
3                  282             True
4                  286            False
...                ...              ...
1169               275            False
1170               265            False
1171               291             True
1172               281            False
1173               297            False

[1174 rows x 2 columns]

(e) Quantas amostras estão presentes nessa tabela? Utilize o método *.shape* e a função *len( )*.

In [35]:
# Usando o método shape (Substitua os ### abaixo pelas declarações adeaquadas):
print(df5.shape)

# Usando a função len (Substitua os ### abaixo pelas declarações adeaquadas):
print(len(df5))

(1174, 6)
1174

6. Em Python, o valor booleano *True* tem valor matemático igual a 1, enquanto o valor *False* tem valor matemático igual a zero. Com base nisso:

(a) Calcule *True* + 5

In [36]:
True + 5

6

(b) Calcule *False* - 8

In [40]:
False - 8

-8

(c) Calcule *False* $\times$ 2

In [41]:
False * 2

0

(d) Calcule 10 $\div$ *True*

In [42]:
10 / True

10.0

7. Na próxima questão usaremos os dados das projeções desenvolvidas pelo IBGE. Os dados estão presentes no seguinte *link*:

> [https://raw.githubusercontent.com/nightlySnoopy/database/main/projections.csv](https://raw.githubusercontent.com/nightlySnoopy/database/main/projections.csv)

(a) Atribua esses dados ao nome *df7*.

In [70]:
df7 = pd.read_csv("https://raw.githubusercontent.com/nightlySnoopy/database/main/projections.csv")

(b) Visualize as 4 últimas linhas dessa tabela.

In [61]:
df7.tail(4)

,G.Etário,2010,2011,2012,2013,2014,2015,2016,2017,2018,...,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060
15,75-79,2597990,2688798,2797237,2913384,3023576,3121818,3211601,3292375,3376250,...,9496727,9752138,10030863,10307408,10564467,10804204,11027068,11224976,11388373,11511971
16,80-84,1689444,1727063,1764898,1807817,1861166,1926871,2004365,2095235,2191860,...,7075422,7159683,7246694,7358416,7506972,7687508,7899218,8128899,8356311,8567809
17,85-89,830529,901360,954570,996763,1032554,1065148,1097017,1129489,1165517,...,4659375,4764254,4861528,4950167,5030651,5103867,5168499,5235780,5321722,5434778
18,90+,455191,459166,484603,521252,562349,603580,645377,688657,731945,...,3794831,3953061,4110366,4263976,4412193,4556131,4697023,4833076,4962058,5083408

(c) Quantas linhas e quantas colunas tem essa tabela?

In [50]:
df7.shape

(19, 52)

(d) Elimine a coluna **2010** de *df7*. Atribua essa nova tabela ao nome *df7d* e visualize o resultado.

In [62]:
df7d = df7.drop(columns=["2010"])
df7d

,G.Etário,2011,2012,2013,2014,2015,2016,2017,2018,2019,...,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060
0,0-4,14697433,14624301,14567170,14570070,14677159,14715112,14720776,14787557,14798332,...,11547982,11473958,11397201,11317212,11233863,11147191,11057520,10965028,10870292,10774218
1,5-9,15600504,15387507,15203145,15029641,14824271,14664918,14593299,14537829,14542132,...,11891973,11820071,11749531,11679356,11608504,11536459,11462615,11386046,11306224,11223031
2,10-14,17216843,16880174,16495325,16131984,15840860,15577214,15365237,15182024,15009676,...,12293466,12202305,12116445,12035156,11957694,11883455,11811703,11741278,11671246,11600532
3,15-19,17238401,17315601,17402809,17424089,17334096,17155615,16821630,16439846,16079464,...,12796510,12681921,12572557,12467934,12367551,12271531,12180736,12095228,12014265,11937109
4,20-24,17396868,17296030,17195219,17124785,17100769,17122881,17203520,17294780,17319853,...,13385549,13251456,13120499,12993545,12870528,12751775,12637977,12529386,12425516,12325847
5,25-29,17423848,17454135,17436877,17391346,17331851,17256322,17161679,17068593,17004904,...,14010163,13875462,13738287,13600246,13463536,13328803,13195813,13065893,12939931,12817887
6,30-34,16275019,16567575,16822855,17028854,17178656,17271648,17306947,17296659,17258318,...,14431957,14408126,14307058,14195853,14075191,13946610,13813084,13677088,13540196,13404578
7,35-39,14350827,14689558,15066579,15441748,15787821,16107943,16402815,16661965,16872342,...,14341981,14353071,14422945,14437977,14376076,14353778,14330671,14230768,14120755,14001307
8,40-44,13311309,13414041,13519509,13668343,13884283,14161178,14500831,14879035,15255513,...,14174828,14114206,14068807,14080737,14192649,14236987,14248844,14318948,14334584,14273861
9,45-49,12218181,12426314,12615601,12784211,12933598,13064058,13171048,13281287,13434076,...,14864721,14670479,14503796,14347422,14160785,14018586,13960052,13916591,13929788,14041783
10,50-54,10574366,10868062,11152415,11419933,11666086,11892707,12102371,12293932,12465329,...,16098244,15794311,15445094,15116301,14855005,14618039,14428117,14265353,14112793,13930535
11,55-59,8679820,8977656,9278724,9579705,9877881,10172542,10463716,10746091,11012111,...,15712380,15798347,15891980,15924009,15853162,15701406,15406171,15066946,14747850,14494713
12,60-64,6859058,7119004,7379912,7647936,7926230,8211893,8503042,8797470,9091910,...,15285499,15218052,15149158,15105746,15102049,15137666,15222586,15314436,15346470,15279016
13,65-69,5095516,5318713,5565313,5819304,6071240,6322755,6572590,6823731,7081680,...,14477368,14526754,14535915,14520894,14493445,14451348,14390212,14327671,14289289,14288480
14,70-74,3889352,3974955,4063519,4175947,4323465,4501441,4709484,4938529,5174388,...,12380193,12631212,12853724,13037277,13176002,13269879,13317776,13328895,13317878,13295484
15,75-79,2688798,2797237,2913384,3023576,3121818,3211601,3292375,3376250,3480536,...,9496727,9752138,10030863,10307408,10564467,10804204,11027068,11224976,11388373,11511971
16,80-84,1727063,1764898,1807817,1861166,1926871,2004365,2095235,2191860,2283815,...,7075422,7159683,7246694,7358416,7506972,7687508,7899218,8128899,8356311,8567809
17,85-89,901360,954570,996763,1032554,1065148,1097017,1129489,1165517,1208442,...,4659375,4764254,4861528,4950167,5030651,5103867,5168499,5235780,5321722,5434778
18,90+,459166,484603,521252,562349,603580,645377,688657,731945,774304,...,3794831,3953061,4110366,4263976,4412193,4556131,4697023,4833076,4962058,5083408

(e) Elimine as colunas 2011 a 2013 e 2015 da tabela **df7d** atribuindo essa nova tabela ao nome **df7e**. Visualize o resultado.

In [63]:
df7e = df7d.drop(columns=["2011","2013","2015"])
df7e

,G.Etário,2012,2014,2016,2017,2018,2019,2020,2021,2022,...,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060
0,0-4,14624301,14570070,14715112,14720776,14787557,14798332,14730311,14703281,14675523,...,11547982,11473958,11397201,11317212,11233863,11147191,11057520,10965028,10870292,10774218
1,5-9,15387507,15029641,14664918,14593299,14537829,14542132,14650311,14689394,14695773,...,11891973,11820071,11749531,11679356,11608504,11536459,11462615,11386046,11306224,11223031
2,10-14,16880174,16131984,15577214,15365237,15182024,15009676,14805478,14647164,14576191,...,12293466,12202305,12116445,12035156,11957694,11883455,11811703,11741278,11671246,11600532
3,15-19,17315601,17424089,17155615,16821630,16439846,16079464,15790863,15529387,15318916,...,12796510,12681921,12572557,12467934,12367551,12271531,12180736,12095228,12014265,11937109
4,20-24,17296030,17124785,17122881,17203520,17294780,17319853,17233266,17057794,16726717,...,13385549,13251456,13120499,12993545,12870528,12751775,12637977,12529386,12425516,12325847
5,25-29,17454135,17391346,17256322,17161679,17068593,17004904,16985866,17011218,17092427,...,14010163,13875462,13738287,13600246,13463536,13328803,13195813,13065893,12939931,12817887
6,30-34,16567575,17028854,17271648,17306947,17296659,17258318,17205416,17135646,17044190,...,14431957,14408126,14307058,14195853,14075191,13946610,13813084,13677088,13540196,13404578
7,35-39,14689558,15441748,16107943,16402815,16661965,16872342,17026545,17123723,17161844,...,14341981,14353071,14422945,14437977,14376076,14353778,14330671,14230768,14120755,14001307
8,40-44,13414041,13668343,14161178,14500831,14879035,15255513,15602974,15924417,16219710,...,14174828,14114206,14068807,14080737,14192649,14236987,14248844,14318948,14334584,14273861
9,45-49,12426314,12784211,13064058,13171048,13281287,13434076,13652504,13930420,14269004,...,14864721,14670479,14503796,14347422,14160785,14018586,13960052,13916591,13929788,14041783
10,50-54,10868062,11419933,11892707,12102371,12293932,12465329,12617804,12751592,12861867,...,16098244,15794311,15445094,15116301,14855005,14618039,14428117,14265353,14112793,13930535
11,55-59,8977656,9579705,10172542,10463716,10746091,11012111,11257277,11483368,11692613,...,15712380,15798347,15891980,15924009,15853162,15701406,15406171,15066946,14747850,14494713
12,60-64,7119004,7647936,8211893,8503042,8797470,9091910,9383728,9672175,9957156,...,15285499,15218052,15149158,15105746,15102049,15137666,15222586,15314436,15346470,15279016
13,65-69,5318713,5819304,6322755,6572590,6823731,7081680,7349244,7623733,7903288,...,14477368,14526754,14535915,14520894,14493445,14451348,14390212,14327671,14289289,14288480
14,70-74,3974955,4175947,4501441,4709484,4938529,5174388,5408663,5642901,5876091,...,12380193,12631212,12853724,13037277,13176002,13269879,13317776,13328895,13317878,13295484
15,75-79,2797237,3023576,3211601,3292375,3376250,3480536,3614389,3774018,3959070,...,9496727,9752138,10030863,10307408,10564467,10804204,11027068,11224976,11388373,11511971
16,80-84,1764898,1861166,2004365,2095235,2191860,2283815,2366558,2443191,2513706,...,7075422,7159683,7246694,7358416,7506972,7687508,7899218,8128899,8356311,8567809
17,85-89,954570,1032554,1097017,1129489,1165517,1208442,1259330,1318006,1385731,...,4659375,4764254,4861528,4950167,5030651,5103867,5168499,5235780,5321722,5434778
18,90+,484603,562349,645377,688657,731945,774304,815165,856211,898723,...,3794831,3953061,4110366,4263976,4412193,4556131,4697023,4833076,4962058,5083408

(f) Verifique os rótulos (nomes) das colunas da tabela **df7**.

In [71]:
df7.columns

Index(['G.Etário', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025',
       '2026', '2027', '2028', '2029', '2030', '2031', '2032', '2033', '2034',
       '2035', '2036', '2037', '2038', '2039', '2040', '2041', '2042', '2043',
       '2044', '2045', '2046', '2047', '2048', '2049', '2050', '2051', '2052',
       '2053', '2054', '2055', '2056', '2057', '2058', '2059', '2060'],
      dtype='object')

(g) Crie uma **lista** de nome **deletar** cujos elementos são os *strings* dos valores de 2025 até 2060. Dica: Aproveite o <ins>resultado do item anterior</ins>.

In [73]:
deletar=['2025',
       '2026', '2027', '2028', '2029', '2030', '2031', '2032', '2033', '2034',
       '2035', '2036', '2037', '2038', '2039', '2040', '2041', '2042', '2043',
       '2044', '2045', '2046', '2047', '2048', '2049', '2050', '2051', '2052',
       '2053', '2054', '2055', '2056', '2057', '2058', '2059', '2060']

(h) Elimine as colunas de 2025 a 2060 da tabela **df7** atribuindo essa nova tabela ao próprio **df7**. Visualize o resultado. Dica: utilize o resultado do item anterior.

In [74]:
df7 = df7.drop(columns=deletar)
df7

,G.Etário,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,0-4,14858280,14697433,14624301,14567170,14570070,14677159,14715112,14720776,14787557,14798332,14730311,14703281,14675523,14569055,14452355
1,5-9,15865195,15600504,15387507,15203145,15029641,14824271,14664918,14593299,14537829,14542132,14650311,14689394,14695773,14762671,14773628
2,10-14,17397304,17216843,16880174,16495325,16131984,15840860,15577214,15365237,15182024,15009676,14805478,14647164,14576191,14520972,14525347
3,15-19,17219086,17238401,17315601,17402809,17424089,17334096,17155615,16821630,16439846,16079464,15790863,15529387,15318916,15136923,14965724
4,20-24,17476779,17396868,17296030,17195219,17124785,17100769,17122881,17203520,17294780,17319853,17233266,17057794,16726717,16347561,15989803
5,25-29,17334110,17423848,17454135,17436877,17391346,17331851,17256322,17161679,17068593,17004904,16985866,17011218,17092427,17182193,17206153
6,30-34,15955949,16275019,16567575,16822855,17028854,17178656,17271648,17306947,17296659,17258318,17205416,17135646,17044190,16951251,16886952
7,35-39,14075108,14350827,14689558,15066579,15441748,15787821,16107943,16402815,16661965,16872342,17026545,17123723,17161844,17152616,17115112
8,40-44,13184170,13311309,13414041,13519509,13668343,13884283,14161178,14500831,14879035,15255513,15602974,15924417,16219710,16478229,16688213
9,45-49,11992439,12218181,12426314,12615601,12784211,12933598,13064058,13171048,13281287,13434076,13652504,13930420,14269004,14644402,15017933
10,50-54,10276773,10574366,10868062,11152415,11419933,11666086,11892707,12102371,12293932,12465329,12617804,12751592,12861867,12974530,13128538
11,55-59,8387564,8679820,8977656,9278724,9579705,9877881,10172542,10463716,10746091,11012111,11257277,11483368,11692613,11883880,12055490
12,60-64,6596741,6859058,7119004,7379912,7647936,7926230,8211893,8503042,8797470,9091910,9383728,9672175,9957156,10233460,10493988
13,65-69,4905988,5095516,5318713,5565313,5819304,6071240,6322755,6572590,6823731,7081680,7349244,7623733,7903288,8185834,8468411
14,70-74,3792042,3889352,3974955,4063519,4175947,4323465,4501441,4709484,4938529,5174388,5408663,5642901,5876091,6110754,6351769
15,75-79,2597990,2688798,2797237,2913384,3023576,3121818,3211601,3292375,3376250,3480536,3614389,3774018,3959070,4161906,4370673
16,80-84,1689444,1727063,1764898,1807817,1861166,1926871,2004365,2095235,2191860,2283815,2366558,2443191,2513706,2587330,2677251
17,85-89,830529,901360,954570,996763,1032554,1065148,1097017,1129489,1165517,1208442,1259330,1318006,1385731,1457236,1525459
18,90+,455191,459166,484603,521252,562349,603580,645377,688657,731945,774304,815165,856211,898723,943466,991663

(i) A coluna *G.Etário* tem valores classificados como inteiros? E as outras colunas? Todas as linhas de todas as colunas estão preenchidas? Verifique usando o método adequado.

In [76]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   G.Etário  19 non-null     object
 1   2010      19 non-null     int64
 2   2011      19 non-null     int64
 3   2012      19 non-null     int64
 4   2013      19 non-null     int64
 5   2014      19 non-null     int64
 6   2015      19 non-null     int64
 7   2016      19 non-null     int64
 8   2017      19 non-null     int64
 9   2018      19 non-null     int64
 10  2019      19 non-null     int64
 11  2020      19 non-null     int64
 12  2021      19 non-null     int64
 13  2022      19 non-null     int64
 14  2023      19 non-null     int64
 15  2024      19 non-null     int64
dtypes: int64(15), object(1)
memory usage: 2.5+ KB

8. A tabela que será utilizada neste exercício são informações de laptops presentes no site espanhol [www.pccomponentes.com](www.pccomponentes.com). Nela se encontram todos os laptops presentes no mercado no dia 25 de junho de 2023.

(a) Atribua a tabela

> [https://raw.githubusercontent.com/nightlySnoopy/database/main/laptops.csv](https://raw.githubusercontent.com/nightlySnoopy/database/main/laptops.csv)

ao nome *df8*. Visualize as 5 primeiras linhas dela.

In [80]:
tab= ("https://raw.githubusercontent.com/nightlySnoopy/database/main/laptops.csv")
df8 = pd.read_csv(tab)
df8.head(5)

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01

(b) Verifique as classificações dos valores e se todas as linhas estão preenchidas nessa tabela.

In [81]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Laptop        2160 non-null   object
 1   Status        2160 non-null   object
 2   Brand         2160 non-null   object
 3   Model         2160 non-null   object
 4   CPU           2160 non-null   object
 5   RAM           2160 non-null   int64
 6   Storage       2160 non-null   int64
 7   Storage type  2118 non-null   object
 8   GPU           789 non-null    object
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB

(c) No total, quantas linhas estão presentes nessa tabela?

In [1]:
# @title  { run: "auto", vertical-output: true }
q8c = # @param {type:"integer"}

answer = 2160

if q8c == answer:
  print('Resposta correta.')

else:
  print('Reveja a sua resposta.')

SyntaxError: ignored

(d) Sabendo que a coluna *Screen* tem a medida da tela em polegadas, quantos laptops apresentam informações sobre essa característica?

In [ ]:
# @title  { run: "auto", vertical-output: true }
q8d = # @param {type:"integer"}

answer = 2156

if q8d == answer:
  print('Resposta correta.')

else:
  print('Reveja a sua resposta.')

(e) Em quantos computadores estão faltando a informação do GPU?

In [ ]:
# @title  { run: "auto", vertical-output: true }
q8e = # @param {type:"integer"}

answer = 1371

if q8e == answer:
  print('Resposta correta.')

else:
  print('Reveja a sua resposta.')